# Generated by Django 6.0.2 on 2026-02-10 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('coeff', models.IntegerField()),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CeleryApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CeleryApp.matiere')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CeleryApp.utilisateur')),
            ],
        ),
    ]
